// loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// theming
export const TOGGLE_THEME = 'TOGGLE_THEME';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_LOADING_ENDED = 'LOGIN_LOADING_ENDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_OUT = 'LOG_OUT';

// notes
export const GET_NOTES_REQUEST = 'GET_NOTES_REQUEST';
export const GET_NOTES_RESPONSE = 'GET_NOTES_RESPONSE';
export const GET_NOTES_FAILED = 'GET_NOTES_FAILED';

export const PATCH_NOTE_REQUEST = 'PATCH_NOTE_REQUEST';
export const PATCH_NOTE_RESPONSE = 'PATCH_NOTE_RESPONSE';
export const PATCH_NOTE_FAILED = 'PATCH_NOTE_FAILED';

export const POST_NOTE_REQUEST = 'POST_NOTE_REQUEST';
export const POST_NOTE_RESPONSE = 'POST_NOTE_RESPONSE';
export const POST_NOTE_FAILED = 'POST_NOTE_FAILED';
